// automatically generated by the FlatBuffers compiler, do not modify

package SDD.Response;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Task extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_11_1(); }
  public static Task getRootAsTask(ByteBuffer _bb) { return getRootAsTask(_bb, new Task()); }
  public static Task getRootAsTask(ByteBuffer _bb, Task obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Task __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte resultType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public boolean mutateResultType(byte result_type) { int o = __offset(4); if (o != 0) { bb.put(o + bb_pos, result_type); return true; } else { return false; } }
  public Table result(Table obj) { int o = __offset(6); return o != 0 ? __union(obj, o) : null; }

  public static int createTask(FlatBufferBuilder builder,
      byte result_type,
      int resultOffset) {
    builder.startTable(2);
    Task.addResult(builder, resultOffset);
    Task.addResultType(builder, result_type);
    return Task.endTask(builder);
  }

  public static void startTask(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addResultType(FlatBufferBuilder builder, byte resultType) { builder.addByte(0, resultType, 0); }
  public static void addResult(FlatBufferBuilder builder, int resultOffset) { builder.addOffset(1, resultOffset, 0); }
  public static int endTask(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
}

