// automatically generated by the FlatBuffers compiler, do not modify

package SDD.Client;

public final class EventUnion {
  private EventUnion() { }
  public static final byte NONE = 0;
  public static final byte Move = 1;

  public static final String[] names = { "NONE", "Move", };

  public static String name(int e) { return names[e]; }
}

