// automatically generated by the FlatBuffers compiler, do not modify

package SDD.Client;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Move extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_11_1(); }
  public static Move getRootAsMove(ByteBuffer _bb) { return getRootAsMove(_bb, new Move()); }
  public static Move getRootAsMove(ByteBuffer _bb, Move obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Move __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int direction() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateDirection(int direction) { int o = __offset(4); if (o != 0) { bb.put(o + bb_pos, (byte)direction); return true; } else { return false; } }

  public static int createMove(FlatBufferBuilder builder,
      int direction) {
    builder.startTable(1);
    Move.addDirection(builder, direction);
    return Move.endMove(builder);
  }

  public static void startMove(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addDirection(FlatBufferBuilder builder, int direction) { builder.addByte(0, (byte)direction, (byte)0); }
  public static int endMove(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
}

