[package]
name = "super-dungeons-destroyers-server"
version = "0.1.0"
authors = ["Adrien 'Litarvan' Navratil <adrien1975@live.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
