// automatically generated by the FlatBuffers compiler, do not modify

package SDD.Server;

public final class Content {
  private Content() { }
  public static final byte NONE = 0;
  public static final byte Pong = 1;
  public static final byte Environment = 2;

  public static final String[] names = { "NONE", "Pong", "Environment", };

  public static String name(int e) { return names[e]; }
}

