// automatically generated by the FlatBuffers compiler, do not modify

package SDD.Server;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class EntityMove extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_11_1(); }
  public static EntityMove getRootAsEntityMove(ByteBuffer _bb) { return getRootAsEntityMove(_bb, new EntityMove()); }
  public static EntityMove getRootAsEntityMove(ByteBuffer _bb, EntityMove obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public EntityMove __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long entityId() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public boolean mutateEntityId(long entity_id) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, entity_id); return true; } else { return false; } }
  public int direction() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateDirection(int direction) { int o = __offset(6); if (o != 0) { bb.put(o + bb_pos, (byte)direction); return true; } else { return false; } }

  public static int createEntityMove(FlatBufferBuilder builder,
      long entity_id,
      int direction) {
    builder.startTable(2);
    EntityMove.addEntityId(builder, entity_id);
    EntityMove.addDirection(builder, direction);
    return EntityMove.endEntityMove(builder);
  }

  public static void startEntityMove(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addEntityId(FlatBufferBuilder builder, long entityId) { builder.addLong(0, entityId, 0L); }
  public static void addDirection(FlatBufferBuilder builder, int direction) { builder.addByte(1, (byte)direction, (byte)0); }
  public static int endEntityMove(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
}

