// automatically generated by the FlatBuffers compiler, do not modify

package SDD.Server;

public final class EventUnion {
  private EventUnion() { }
  public static final byte NONE = 0;
  /**
   * When you're successfully connected.
   */
  public static final byte Welcome = 1;
  /**
   * When someone join the game.
   */
  public static final byte Join = 2;
  /**
   * When someone leave the game.
   */
  public static final byte Leave = 3;
  /**
   * When a entity move.
   */
  public static final byte EntityMove = 4;
  /**
   * When an entity was created.
   */
  public static final byte EntityCreate = 5;
  /**
   * When you enter a new area.
   */
  public static final byte ZoneInfo = 6;

  public static final String[] names = { "NONE", "Welcome", "Join", "Leave", "EntityMove", "EntityCreate", "ZoneInfo", };

  public static String name(int e) { return names[e]; }
}

