// automatically generated by the FlatBuffers compiler, do not modify

package SDD.Server;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Leave extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_11_1(); }
  public static Leave getRootAsLeave(ByteBuffer _bb) { return getRootAsLeave(_bb, new Leave()); }
  public static Leave getRootAsLeave(ByteBuffer _bb, Leave obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Leave __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SDD.Common.Entity player() { return player(new SDD.Common.Entity()); }
  public SDD.Common.Entity player(SDD.Common.Entity obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createLeave(FlatBufferBuilder builder,
      int playerOffset) {
    builder.startTable(1);
    Leave.addPlayer(builder, playerOffset);
    return Leave.endLeave(builder);
  }

  public static void startLeave(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addPlayer(FlatBufferBuilder builder, int playerOffset) { builder.addOffset(0, playerOffset, 0); }
  public static int endLeave(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // player
    return o;
  }
}

