// automatically generated by the FlatBuffers compiler, do not modify

package SDD.Server;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Welcome extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_11_1(); }
  public static Welcome getRootAsWelcome(ByteBuffer _bb) { return getRootAsWelcome(_bb, new Welcome()); }
  public static Welcome getRootAsWelcome(ByteBuffer _bb, Welcome obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Welcome __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SDD.Common.Entity me() { return me(new SDD.Common.Entity()); }
  public SDD.Common.Entity me(SDD.Common.Entity obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createWelcome(FlatBufferBuilder builder,
      int meOffset) {
    builder.startTable(1);
    Welcome.addMe(builder, meOffset);
    return Welcome.endWelcome(builder);
  }

  public static void startWelcome(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addMe(FlatBufferBuilder builder, int meOffset) { builder.addOffset(0, meOffset, 0); }
  public static int endWelcome(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // me
    return o;
  }
}

