// automatically generated by the FlatBuffers compiler, do not modify

package SDD.Server;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ZoneInfo extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_11_1(); }
  public static ZoneInfo getRootAsZoneInfo(ByteBuffer _bb) { return getRootAsZoneInfo(_bb, new ZoneInfo()); }
  public static ZoneInfo getRootAsZoneInfo(ByteBuffer _bb, ZoneInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ZoneInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int level() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateLevel(int level) { int o = __offset(4); if (o != 0) { bb.put(o + bb_pos, (byte)level); return true; } else { return false; } }
  public int environment() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateEnvironment(int environment) { int o = __offset(6); if (o != 0) { bb.put(o + bb_pos, (byte)environment); return true; } else { return false; } }
  public SDD.Common.Entity entities(int j) { return entities(new SDD.Common.Entity(), j); }
  public SDD.Common.Entity entities(SDD.Common.Entity obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int entitiesLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }

  public static int createZoneInfo(FlatBufferBuilder builder,
      int level,
      int environment,
      int entitiesOffset) {
    builder.startTable(3);
    ZoneInfo.addEntities(builder, entitiesOffset);
    ZoneInfo.addEnvironment(builder, environment);
    ZoneInfo.addLevel(builder, level);
    return ZoneInfo.endZoneInfo(builder);
  }

  public static void startZoneInfo(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addLevel(FlatBufferBuilder builder, int level) { builder.addByte(0, (byte)level, (byte)0); }
  public static void addEnvironment(FlatBufferBuilder builder, int environment) { builder.addByte(1, (byte)environment, (byte)0); }
  public static void addEntities(FlatBufferBuilder builder, int entitiesOffset) { builder.addOffset(2, entitiesOffset, 0); }
  public static int createEntitiesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startEntitiesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endZoneInfo(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
}

