// automatically generated by the FlatBuffers compiler, do not modify

package SDD.Request;

public final class Action {
  private Action() { }
  public static final byte NONE = 0;
  public static final byte Ping = 1;

  public static final String[] names = { "NONE", "Ping", };

  public static String name(int e) { return names[e]; }
}

