// automatically generated by the FlatBuffers compiler, do not modify

package SDD.Request;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Request extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_11_1(); }
  public static Request getRootAsRequest(ByteBuffer _bb) { return getRootAsRequest(_bb, new Request()); }
  public static Request getRootAsRequest(ByteBuffer _bb, Request obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Request __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SDD.Request.Task tasks(int j) { return tasks(new SDD.Request.Task(), j); }
  public SDD.Request.Task tasks(SDD.Request.Task obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int tasksLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createRequest(FlatBufferBuilder builder,
      int tasksOffset) {
    builder.startTable(1);
    Request.addTasks(builder, tasksOffset);
    return Request.endRequest(builder);
  }

  public static void startRequest(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addTasks(FlatBufferBuilder builder, int tasksOffset) { builder.addOffset(0, tasksOffset, 0); }
  public static int createTasksVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startTasksVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // tasks
    return o;
  }
  public static void finishRequestBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedRequestBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }
}

