// automatically generated by the FlatBuffers compiler, do not modify

package SDD.Request;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Task extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_11_1(); }
  public static Task getRootAsTask(ByteBuffer _bb) { return getRootAsTask(_bb, new Task()); }
  public static Task getRootAsTask(ByteBuffer _bb, Task obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Task __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte actionType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table action(Table obj) { int o = __offset(6); return o != 0 ? __union(obj, o) : null; }

  public static int createTask(FlatBufferBuilder builder,
      byte action_type,
      int actionOffset) {
    builder.startTable(2);
    Task.addAction(builder, actionOffset);
    Task.addActionType(builder, action_type);
    return Task.endTask(builder);
  }

  public static void startTask(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addActionType(FlatBufferBuilder builder, byte actionType) { builder.addByte(0, actionType, 0); }
  public static void addAction(FlatBufferBuilder builder, int actionOffset) { builder.addOffset(1, actionOffset, 0); }
  public static int endTask(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
}

