// automatically generated by the FlatBuffers compiler, do not modify

package SDD.Common;

public final class Direction {
  private Direction() { }
  public static final byte Right = 0;
  public static final byte Left = 1;
  public static final byte Down = 2;
  public static final byte Up = 3;

  public static final String[] names = { "Right", "Left", "Down", "Up", };

  public static String name(int e) { return names[e]; }
}

