// automatically generated by the FlatBuffers compiler, do not modify

package SDD.Common;

public final class EntityKind {
  private EntityKind() { }
  public static final byte NONE = 0;
  public static final byte Player = 1;

  public static final String[] names = { "NONE", "Player", };

  public static String name(int e) { return names[e]; }
}

