// automatically generated by the FlatBuffers compiler, do not modify

package SDD.Common;

public final class RoomKind {
    private RoomKind() {
    }

    public static final byte TestMap = 0;

    public static final String[] names = {"TestMap",};

    public static String name(int e) {
        return names[e];
    }
}

