// automatically generated by the FlatBuffers compiler, do not modify

package SDD.Mob;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Struct;

import java.nio.ByteBuffer;

@SuppressWarnings("unused")
public final class Vec3 extends Struct {
    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public Vec3 __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public float x() {
        return bb.getFloat(bb_pos + 0);
    }

    public void mutateX(float x) {
        bb.putFloat(bb_pos + 0, x);
    }

    public float y() {
        return bb.getFloat(bb_pos + 4);
    }

    public void mutateY(float y) {
        bb.putFloat(bb_pos + 4, y);
    }

    public int orientation() {
        return bb.getInt(bb_pos + 8);
    }

    public void mutateOrientation(int orientation) {
        bb.putInt(bb_pos + 8, orientation);
    }

    public static int createVec3(FlatBufferBuilder builder, float x, float y, int orientation) {
        builder.prep(4, 12);
        builder.putInt(orientation);
        builder.putFloat(y);
        builder.putFloat(x);
        return builder.offset();
    }
}

